name = "MedicalTutorials"
uuid = "c4c020fc-6d91-4289-b833-39d376a8f565"
authors = ["Dale <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
